// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/user/karyawan/:slug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/[slug].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/[slug].put').default>>>>
    }
    '/api/user/karyawan/departemen/userdepartemenanak': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/departemen/userdepartemenanak.get').default>>>>
    }
    '/api/user/karyawan/departemen/userdepartemenanestesi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/departemen/userdepartemenanestesi.get').default>>>>
    }
    '/api/user/karyawan/departemen/userdepartemenbagiankeuangan': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/departemen/userdepartemenbagiankeuangan.get').default>>>>
    }
    '/api/user/karyawan/departemen/userdepartemenbankdarah': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/departemen/userdepartemenbankdarah.get').default>>>>
    }
    '/api/user/karyawan/departemen/userdepartemenbedah': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/departemen/userdepartemenbedah.get').default>>>>
    }
    '/api/user/karyawan/detailkaryawan': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/detailkaryawan.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit1': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit1.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit42': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit42.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit46': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit46.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit53': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit53.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit55': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit55.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit60': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit60.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit61': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit61.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit62': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit62.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit63': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit63.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit70': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit70.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit71': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit71.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit84': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit84.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit85': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit85.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit87': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit87.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit88': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit88.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit89': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit89.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit90': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit90.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit91': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit91.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit92': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit92.get').default>>>>
    }
    '/api/user/karyawan/kdunit/userkdunit93': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/kdunit/userkdunit93.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole1': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole1.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole10': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole10.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole11': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole11.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole12': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole12.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole13': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole13.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole14': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole14.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole15': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole15.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole2': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole2.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole3': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole3.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole4': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole4.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole5': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole5.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole6': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole6.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole7': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole7.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole8': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole8.get').default>>>>
    }
    '/api/user/karyawan/roles/userrole9': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/roles/userrole9.get').default>>>>
    }
    '/api/user/karyawan/userrs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/userrs.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/userrs.post').default>>>>
    }
    '/api/user/karyawan/userrsbyid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/karyawan/userrsbyid.get').default>>>>
    }
    '/api/user/pasien/:slug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/pasien/[slug].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/pasien/[slug].put').default>>>>
    }
    '/api/user/pasien/pasienrs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/pasien/pasienrs.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/pasien/pasienrs.post').default>>>>
    }
    '/api/user/pasien/pasienrsbyid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/pasien/pasienrsbyid.get').default>>>>
    }
    '/api/userjoin/join': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/userjoin/join.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}